---
- name: INSTALL | ISCSI packages for Pure FA
  ansible.builtin.yum:
    name: "{{ iscsi_packages }}"
    state: present
  when: ansible_distribution_major_version|int <= 7

- name: INSTALL | ISCSI packages for Pure FA
  ansible.builtin.dnf:
    name: "{{ iscsi_packages }}"
    state: present
  when: ansible_distribution_major_version|int >= 8

